version: '3.8'

services:
  server:
    build: ./server
    environment:
      DB_USER: qatest
      DB_HOST: db
      DB_NAME: todo_db
      DB_PASSWORD: meu_banco_todo
      DB_PORT: 5432
      SERVER_PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: qatest
      POSTGRES_PASSWORD: meu_banco_todo
      POSTGRES_DB: todo_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qatest -d todo_db"] 
      interval: 5s
      timeout: 5s
      retries: 5

  cypress:
    image: cypress/included:12.17.1
    depends_on:
      client:
        condition: service_healthy  # Se você tiver um healthcheck no frontend
      server:
        condition: service_healthy
    environment:
      CYPRESS_baseUrl: http://client:80  # Nome do serviço do frontend na rede Docker
    volumes:
      - ./client/cypress:/e2e/cypress
      - ./client/cypress.config.js:/e2e/cypress.config.js
    command: npx cypress run
    
volumes:
  postgres_data: